### ISSUE TITLE
Add exception handling to AMQP binding

### ISSUE THREAD

**Issue by hekonsek** [iotbricks/iotbricks#18] opened 2017-09-20 15:34 UTC

**Comment by ctron** [comment] 2017-09-21 08:21
Ok so after chatting a bit with @ppatierno my suggestion would be use the AMQP feature of rejecting the message. This way we have a "standard AMQP" way of doing things and don't need to do much definition on the wire side, as there already is an `ErrorCondition` type for doing that.

If that approach is fine, I could start working on implementing this on the server and client binding side.

**Comment by ctron** [comment] 2017-09-25 07:44
Hono is using HTTP error codes for signaling result conditions. Which I kind of like, but which sometimes also makes things more complicated. But I think we should consider this approach when making a decision.

**Comment by ctron** [comment] 2017-09-25 08:38
Duplicate of #9 ... as we have some content here, I am closing #9.

**Comment by ppatierno** [comment] 2017-09-25 14:27
I think that we could define as a Symbol something like HTTP codes (i.e. iot:core:created or something like that). It's worth to think about that.

**Comment by ctron** [comment] 2017-09-29 06:55
I think we are done here for the moment. If we need something improved we create a new task.

**Closed as completed by ctron** 2017-09-29 06:55 UTC
Labels: enhancement
